Satyam1923/Spring-Music-Player

LEARN.md

Added a project description so that contributors can easily build the project for them.

Add LEARN.md

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature.yml

This PR solves the issue #37, kindly review it and merge.

feat: updated record of issue forms

---

.github/workflows/greetings.yml

This PR solves the issue #39 , kindly review it and merge.

feat: automated greetings by setting up CI

---

frontend/src/App.css

Fix for https://github.com/Satyam1923/Spring-Music-Player/issues/51
https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/8e9a763f-ce49-40a5-8215-9e493e771fdd

Making layout responsive

---

README.md

Fully updated Readme Documentation
Changes Made
Updated the README.md file to enhance clarity, provide additional information, and improve the overall presentation of the Spring Music Player project repository.
Added detailed descriptions of project features, tech stack, and expected design.
Included clear instructions for setting up the backend and frontend environments.
Integrated visually appealing markdown elements, including images, links, and code snippets.
Enhanced the contributing guidelines and pull request creation process.
Please mark it as GSSoC' 24

Fully updated Readme Documentation   DOC: Improvements in readme and learn documentation (Issue #74) fixed

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx

Issue https://github.com/Satyam1923/Spring-Music-Player/issues/67

Fixed issue 67

---

CONTRIBUTING.md
README.md

Changing as instructed

---

frontend/src/App.jsx

I put the search text in the search box.
Before: 
After:

Fixed Issue #87

---

frontend/src/App.css

Fixed issue : #79 
---
I have changed  scrollbar  accroding figma design.

Fixed Custom scrollbar  #79

---

frontend/src/App.css

fixed issue : #80 
---
**This is best font style for this website design**
**And during the solving  issue no #78 , which is assigned to me , if any  changes require  in font style , i will Definitely change  it.**

fixed and improved  font style align with design   #80 

---

frontend/package-lock.json
frontend/package.json
frontend/postcss.config.js
frontend/src/App.css
frontend/src/App.jsx
frontend/tailwind.config.js

As mentioned in issue https://github.com/Satyam1923/Spring-Music-Player/issues/25

Added Next and Prev, Autoplay next song with shuffle functionality

---

.github/Pull_Request_Template.md

docs: added pr template

---

frontend/src/App.css
frontend/src/components/Section3.jsx

This Pr is about to fixes the unexpected behaviour of text paragraph this was fixed by changing some css .
closes : #171  
Changes max-height of card2 to 20rem
removed height:100% from div under card2
changes max-height of img from auto to 18rem 

Fixed  Overlapping of paragraph #171

---

backend/index.js
frontend/src/App.css
frontend/src/App.jsx

This PR adds the optioon to filter songs based on the language.
Fixed https://github.com/Satyam1923/Spring-Music-Player/issues/112 issue
So this works something like this first the user can write the name of the song and then from the language dropdown he/she can select the language of it so filtering is preformed in this way.
And if for that particular song there is no language available it displays no data found
https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/11ac5a45-fd52-4bef-9d80-7109b76478cf
[ x] I have performed a self-review of my code
[x ] I have commented my code, particularly in hard-to-understand areas
[x ] My changes generate no new warnings
[x ] I am working on this issue under …

Added the language dropdown feature in the updated branch

---

frontend/src/App.css

"Fixes #119 "
fixed the background gradient as suggested in issue #119 
- [ *] I have performed a self-review of my code
- [ *] I have commented my code, particularly in hard-to-understand areas
- [ *] My changes generate no new warnings
- [ *] I am working on this issue under GSSOC

Added Background gradient from issue #119

---

frontend/src/App.css
frontend/src/App.jsx
frontend/src/components/Background.jsx
frontend/src/components/LinkText.jsx
frontend/src/components/SignIn.jsx
frontend/src/components/SignUp.jsx

Implemented the SignUp and SignIn pages for the application.
- "Fixes #136"

Sign up sign in pages 136

---

frontend/src/App.css

The issue is that styling of search icon and input box is not proper.
I have update the respective CSS properties of search icon and input box to give this website more clean look.
These are the changes that I done.
- [ X] I have performed a self-review of my code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
- [X ] I am working on this issue under GSSOC

search icon and input box styling updated

---

backend/index.js
backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
frontend/src/App.css
frontend/src/App.jsx
frontend/src/components/Section3.jsx
frontend/src/components/Sidebar.jsx
frontend/src/components/sidebar.css
frontend/src/main.jsx
frontend/src/redux/store.js

- Fixes the song not playing
- Fixes Top Artists list displayed 
- Fixes the API problem where the search feature wasn't working
- Updates basic UI (further UI as per Figma FIle will me made in further PR's)
- Updates effect
- now you can search for any song and get the list of songs and can play it on clicking it.
- see the top songs list,it can also be played on clicking on it
- Fixes #205

issue #205

---

frontend/src/App.jsx
frontend/src/components/Home/Home.jsx
frontend/src/components/Navbar.jsx

- Adds new Home page component
- Implements new UI design
"Fixes #220"

Implemented home page design

---

frontend/package-lock.json
frontend/src/App.jsx
frontend/src/components/Home/Home.jsx
frontend/src/components/MusicPlayer.jsx
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/SearchBar.jsx
frontend/src/components/UserIconSection.jsx

Implemented new Search page

---

frontend/package-lock.json
frontend/src/App.jsx
frontend/src/components/Section3.jsx

increased music quality from 12kbps to 320kbps

---

frontend/src/App.css
frontend/src/App.jsx
frontend/src/components/Sidebar.jsx

Removed all unnecessary CSS stylings from website #251

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/Aboutus.css
frontend/src/pages/Aboutus.jsx
frontend/src/pages/Contactus.css
frontend/src/pages/Contactus.jsx

I created a Pages folder and added aboutus.jsx aboutus.css contactus.jsx contactus.css files to it
Fixes #152 
As of now user cannot access this pages ,once footer is created then we can link them to footer
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I am working on this issue under GSSOC

About Us and Contact Us pages were added

---

frontend/src/App.css
frontend/src/App.jsx
frontend/src/components/Settings.css
frontend/src/components/Swiper2.jsx

Fixed the search results stylings

---

frontend/src/App.css

- Fixes the search bar cursor and text aligning to the center by default. 
-Issue #266 
- Fixed a bug in App.css by removing "text-align: center" from class "box1". This allows the text and cursor in the search bar to align to the left.
Any …

Fixed search bar text-align

---

frontend/src/components/Footer.jsx

Solved issue #277 
- [ x] I have performed a self-review of my code
- [ x] I am working on this issue under GSSOC

Added the github icon

---

frontend/src/components/Footer.jsx

Solved Issue #284 
- [x ] I have performed a self-review of my code
- [ x] I am working on this issue under GSSOC

Updated the twitter icon

---

frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/pages/Terms.jsx

Fixes : #294 
I have added the Terms and Policy Page and linked it as well from the footer section as assigned to me.
Added Terms and Policy Page
Here is an SS : 

Issue#294 fixed. Added Terms and Policy Page.

---

frontend/src/pages/Contactus.jsx

- Adds responsiveness to the contact page suitable for both large and small screens.
- Fixes the overflow and margin issues occurring in android devices.
- Updates the code for mobile responsiveness.
Fixes #307 
- Fixed a bug in responsiveness
This is the android look.

Issue#307 fixed. Added responsiveness for the contact page.

---

frontend/src/App.jsx
frontend/src/components/Section3.jsx

Fixed issue #273 
SO when we come back to home page from settings earlier the music used to automatically start but i have fixed that now the music stops after we cam e back to homepage and it starts only when we start it manually.
https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/d40b6ece-8ba0-42f6-a081-ea3dbfd23e17
- [x ] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I am working on this issue under GSSOC

Fixed the automatic playing of music after coming back to homepage 

---

frontend/src/App.jsx
frontend/src/components/Section3.jsx
frontend/src/components/Sidebar.jsx

Allow users to mark songs as favorites for quick access #99

Allow users to mark songs as favorites for quick access

---

frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/pages/Blog.jsx
frontend/src/pages/Culture.jsx

- Adds the Culture and Blog pages as placeholder
- Fixes ...
- Updates the new pages to tailwind css from vanilla css
- Placeholder: "Fixes #280 "
Any additional context …

resolved issue-280

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/components/Auth/Login.jsx
frontend/src/components/Auth/SignUp.jsx
frontend/src/components/Auth/firebase.js
frontend/src/components/Home/Home.jsx
frontend/src/components/UserIconSection.jsx

**This PR does the following:**
- Adds user authentication using Firebase with email and password.
- Fixes the logout button functionality by implementing loaders and toaster notifications.
- Updates the user interface to reflect authentication state changes without needing a page refresh.
**Related Issues:**
- Fixes #243 
**Changes**
- Added Firebase authentication integration for user registration and login.
- Implemented the logout button with a working loader and toaster notifications.
- Updated user interface elements to dynamically show login/logout states.
**Detailed instructions on how to test the changes. Include any setup needed and specific test cases.**
- Pull this branch.
- Run npm install to install dependencies.
- Set up Firebase configuration in the project.
- Run npm …

authentication done using email and password

---

frontend/package-lock.json
frontend/src/App.jsx

- Adds ...
- Fixes ...
- Updates ... …

fix signup page

---

backend/index.js
frontend/package-lock.json
frontend/package.json
frontend/src/Utils.js

- Adds ...
- Fixes ...
- Updates ... …

fix backend api

---

frontend/src/Utils.js

- Adds ...
- Fixes ...
- Updates ... …

fix url format

---

frontend/src/Utils.js

- Adds ...
- Fixes ...
- Updates ... …

fix frontend json format

---

backend/index.js
backend/package-lock.json
frontend/package-lock.json
frontend/package.json
frontend/src/Utils.js
frontend/src/components/Home/Home.jsx
frontend/src/components/MusicPlayer.jsx
frontend/src/components/Search/Search.jsx
frontend/src/httpClient.js

- Adds ...
- Fixes ...
- Updates ... …

Fix backend

---

frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/SearchBar.jsx

- Adds ...
- Fixes ...
- Updates ...
Make sure to check …

hold search page state && fix reload

---

frontend/src/App.jsx
frontend/src/components/Auth/firebase.js
frontend/src/components/Search/SearchBar.jsx
frontend/src/main.jsx

- Adds ...
- Fixes ...
- Updates ... …

fix routing

---

frontend/src/App.jsx
frontend/src/components/Search/SearchBar.jsx

- Adds ...
- Fixes ...
- Updates ... …

routing error

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/aboutcard.jsx
frontend/src/pages/Aboutus.jsx

- Adds ... hover effect
- Fixes ... colour
- Updates ... ui
- Placeholder: "Fixes #330"
Make sure to check off all the …

about us page hover effect

---

frontend/src/App.jsx
frontend/src/components/Home/Home.jsx
frontend/vercel.json

- Adds ...
- Fixes ...
- Updates ... …

Browser Router

---

frontend/src/main.jsx

- Adds ...
- Fixes ...
- Updates ... …

add back preloader

---

README.md

- Adds ...
Login, SignUp page designing in figma
- Placeholder: "Fixes #21"
- Added a new designs in figma

Designing Login, Signup page and User Profile page in Figma #21

---

backend/index.js
frontend/src/components/Search/Search.jsx

- Adds ...
- Fixes ...
- Updates ...
- Placeholder: 
Make …

Backend Integration

---

.gitignore
backend/index.js
backend/routes/getAlbumById.js
backend/routes/getAlbums.js
backend/routes/getArtistById.js
backend/routes/getArtists.js
backend/routes/getPlaylist.js
backend/routes/getPlaylistById.js
backend/routes/search.js
backend/utils.js

- Refactor backend api routes
Make sure to check off all the …

refactor: refactor backend api routes

---

frontend/src/pages/Culture.jsx

I have finished working on issue #342 which was assigned to me.
I have added top genres and artist with prev next buttons to view rest.

Added Top genres and artist on Culture page

---

backend/.gitignore
backend/index.js
backend/package-lock.json
backend/package.json
backend/routes/scheduler.js
backend/routes/schedulerRouter.js

- Adds ...
- Fixes ...
- Updates ... …

node-cron for scheduling

---

backend/routes/scheduler.js
backend/vercel.json

- Adds ...
- Fixes ...
- Updates ... …

Scheduling

---

backend/routes/scheduler.js
backend/vercel.json

- Adds ...
- Fixes ...
- Updates ... …

schedule for 1:05

---

frontend/src/Utils.js
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/SearchBar.jsx

- Adds ...
- Fixes ...
- Updates ...
- Placeholder: 
Make …

add album feature

---

frontend/src/Utils.js
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/SearchBar.jsx

- Adds ...
- Fixes ...
- Updates ...
Make sure to check …

Album search

---

frontend/src/components/Footer.jsx
frontend/src/components/Home/Home.jsx

Related Issue: #376
1. ### **Firebase Integration:**
- Add 10 Artists Manually: Added 10 artists to the Firebase database, each with relevant details such as name and image.
- Fetch Artist Data: Implemented functionality to fetch the names and images of these artists from Firebase, ensuring that the data is dynamically loaded into the application.
- Also added one more field in the user data called img where you can put image of the artists.
2. ### **Enhanced Artist Interaction:**
- Artist Click Event: Users can now click on an artist's name or image in the 'Top Artists' section.
- Dynamic Top Songs: Upon clicking an artist, the 'Top Songs' section updates to display the top songs of the selected artist, providing a more interactive and personalized experience.
- Playable Top Songs: …

Added artists manually and fetching their songs 

---

frontend/src/App.jsx
frontend/src/components/Auth/firebase.js
frontend/src/components/Search/Search.jsx

- This PR adds nested routes for search page search filter
- Placeholder: "Fixes #322 "

Added nested routes for search filter

---

frontend/src/App.jsx
frontend/src/Utils.js
frontend/src/components/Search/SearchSongs.jsx

Implemented songs section for search page
- "Fixes #317 "
Added `SearchSongs` component. Updated nested route in App.jsx.

Adding songs section for Search page

---

frontend/src/App.jsx
frontend/src/Utils.js
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/SearchAlbums.jsx

Added albums page in search page
- Placeholder: "Fixes #412 "

Adding albums section in Search page

---

frontend/src/App.jsx
frontend/src/Utils.js
frontend/src/components/Album.jsx
frontend/src/components/Home/Home.jsx
frontend/src/components/Search/Search.jsx
frontend/src/components/Search/SearchAlbums.jsx

@Satyam1923 
Feat: Create Album ui #298
close #298
- Adds new route `/album/:id`
- Fixes ...
- Updates ...
- Placeholder: "Fixes #298"
- Added a new feature to album card
- when user click on any artist they will redirected to album page of that artist
Add any screenshots that help explain or visualize …

Album page

---

frontend/src/components/aboutcard.jsx
frontend/tailwind.config.js

- Adds better responsiveness to the about us page
- Placeholder: "Fixes #446"
- Fixed a bug in the responsive design of the about us page …

Issue#446 fixed. Updated the about us page responsiveness.

---

README.md

- Fixes minor typographical errors in the documentation.
- Updates the "Contributing" and "Getting Started" sections for clarity and consistency.
- Placeholder: "Fixes #281 "
Corrected "Pleae ensure" to "Please ensure" in the "Contributing" section.
Changed "Access the local server You will receive a link in your terminal." to "Access the local server. You will receive a link in your terminal." in the "Getting Started" section.
2. Review the corrected documentation for any remaining errors.
3. Verify that the changes improve clarity and correctness.

Resolved Documentation for Spring Music Player

---

frontend/src/components/Search/SearchBar.css
frontend/src/components/Search/SearchBar.jsx

Fixes #452 
updated ui of search bar and fix its height and width

updated ui of searchbar

---

frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/pages/Contributors.jsx

"Fixes #461 "
- [ x] I have performed a self-review of my code
- [ x] I am working on this issue under GSSOC
https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/1d35222a-5b72-4e4a-80fe-b048e008801e

Added the contributors page

---

frontend/src/App.jsx
frontend/src/Utils.js
frontend/src/components/Artist.jsx
frontend/src/components/Search/Search.jsx

@Satyam1923 
@saurabhsingh720 
Feat: Design Artist Page #448
close #448
- Adds `artist/:id` page for particular artists
- Fixes ...
- Updates ...
- Placeholder: "Fixes #448"
3. go to search page
4. try to click on partricular artist's 
Add any screenshots that help explain or visualize the …

artist particualr pagw with their songs

---

frontend/src/components/Auth/Login.jsx
frontend/src/components/Auth/StoreSong.js
frontend/src/components/Auth/firebase.js
frontend/src/pages/Preloader.jsx

- Adds ...
- Fixes ...
- Updates ... …

login page updated

---

frontend/src/App.css
frontend/src/components/MusicPlayer.jsx

- Added the small confetti and animation when like button is clicked in music player section
- Fixes issue #492 
https://github.com/user-attachments/assets/3ee6a12f-f7f0-4844-b849-f1bd24dc92be

added the animation when like button is clicked

---

frontend/src/components/MusicPlayer.jsx
frontend/src/components/Search/Search.jsx

Fixed Search-All Top Results song play button working
